package com.example.greendaodemo003;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greendaodemo003.School;

import com.example.greendaodemo003.SchoolDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig schoolDaoConfig;

    private final SchoolDao schoolDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        schoolDaoConfig = daoConfigMap.get(SchoolDao.class).clone();
        schoolDaoConfig.initIdentityScope(type);

        schoolDao = new SchoolDao(schoolDaoConfig, this);

        registerDao(School.class, schoolDao);
    }
    
    public void clear() {
        schoolDaoConfig.clearIdentityScope();
    }

    public SchoolDao getSchoolDao() {
        return schoolDao;
    }

}
